from mock import MagicMock
import docker.errors


def ClientMock():
    def get_container(container_id):
        try:
            return __inspect_container_cmd_return[container_id]
        except KeyError as e:
            raise docker.errors.APIError(e, "dummy", explanation="No such container: {}".format(container_id))
    MockConn = MagicMock()
    MockConn().attach_mock(MagicMock(side_effect=get_container), 'inspect_container')
    MockConn().attach_mock(MagicMock(return_value=__containers_cmd_return), 'containers')
    return MockConn


__containers_cmd_return = [
    {u'Command': u'/runner/init start web',
        u'Created': 1408697397,
        u'Id': u'656ca7c307d178',
        u'Image': u'hmrc/slugrunner:latest',
        u'Names': [u'/ers-checking-frontend-27'],
        u'Ports': [{u'IP': u'0.0.0.0',
                    u'PrivatePort': 8080,
                    u'PublicPort': 9225,
                    u'Type': u'tcp'}],
        u'Status': u'Up 40 minutes'},
    {u'Command': u'/runner/init start web',
        u'Created': 1408696448,
        u'Id': u'eba8bea2600029',
        u'Image': u'hmrc/slugrunner:latest',
        u'Names': [u'/paye_216'],
        u'Ports': [{u'IP': u'0.0.0.0',
                    u'PrivatePort': 8080,
                    u'PublicPort': 9317,
                    u'Type': u'tcp'}],
        u'Status': u'Up 56 minutes'},
    {u'Command': u'/runner/init start web',
        u'Created': 1408640164,
        u'Id': u'1ca0e49fcd60fa',
        u'Image': u'hmrc/slugrunner:latest',
        u'Names': [u'/attorney_46'],
        u'Ports': [],
        u'Status': u'Exited (-1) 56 minutes ago'}]

__inspect_container_cmd_return = {
    "656ca7c307d178": {
        u'Args': [u'start', u'web'],
        u'Config': {u'AttachStderr': False,
                    u'AttachStdin': False,
                    u'AttachStdout': False,
                    u'Cmd': [u'start', u'web'],
                    u'CpuShares': 0,
                    u'Cpuset': u'',
                    u'Domainname': u'',
                    u'Entrypoint': [u'/runner/init'],
                    u'Env': [u'HMRC_CONFIG=-Dapplication.secret=H7dVw$PlJiD)^U,oa4TA1pa]pT:4ETLqbL&2P=n6T~p,A*}^.Y46@PQOV~9(B09Hc]t7-hsf~&@w=zH -Dapplication.log=INFO -Dlogger.resource=/application-json-logger.xml -Dhttp.port=8080 -Dgovuk-tax.Prod.google-analytics.token=UA-00000000-0 -Drun.mode=Prod -Dsession.secure=true -Dsession.httpOnly=true -Dcookie.encryption.key=fqpLDZ4smuDsekHkrEBlCA==',
                             u'JAVA_OPTS=-Xmx256m -Xms256m',
                             u'SLUG_URL=http://example.com/ers-checking-frontend/ers-checking-frontend_27.tgz',
                             u'PORT=8080',
                             u'HOME=/',
                             u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'],
                    u'ExposedPorts': {u'8080/tcp': {}},
                    u'Hostname': u'656ca7c307d1',
                    u'Image': u'hmrc/slugrunner',
                    u'Memory': 0,
                    u'MemorySwap': 0,
                    u'NetworkDisabled': False,
                    u'OnBuild': None,
                    u'OpenStdin': False,
                    u'PortSpecs': None,
                    u'StdinOnce': False,
                    u'Tty': False,
                    u'User': u'',
                    u'Volumes': None,
                    u'WorkingDir': u''},
        u'Created': u'2014-08-22T08:49:57.80805632Z',
        u'Driver': u'aufs',
        u'ExecDriver': u'native-0.2',
        u'HostConfig': {u'Binds': None,
                        u'ContainerIDFile': u'',
                        u'Dns': None,
                        u'DnsSearch': None,
                        u'Links': None,
                        u'LxcConf': [],
                        u'NetworkMode': u'bridge',
                        u'PortBindings': {u'8080/tcp': [{u'HostIp': u'0.0.0.0',
                                                         u'HostPort': u'9225'}]},
                        u'Privileged': False,
                        u'PublishAllPorts': False,
                        u'VolumesFrom': None},
        u'HostnamePath': u'/var/lib/docker/containers/656ca7c307d178/hostname',
        u'HostsPath': u'/var/lib/docker/containers/656ca7c307d178/hosts',
        u'Id': u'656ca7c307d178',
        u'Image': u'c0cd53268e0c7c42bac84b6bf4f51561720c33f5239aa809f1135cc69cc73a2a',
        u'MountLabel': u'',
        u'Name': u'/ers-checking-frontend-27',
        u'NetworkSettings': {u'Bridge': u'docker0',
                             u'Gateway': u'172.17.42.1',
                             u'IPAddress': u'172.17.3.224',
                             u'IPPrefixLen': 16,
                             u'PortMapping': None,
                             u'Ports': {u'8080/tcp': [{u'HostIp': u'0.0.0.0',
                                                       u'HostPort': u'9225'}]}},
        u'Path': u'/runner/init',
        u'ProcessLabel': u'',
        u'ResolvConfPath': u'/etc/resolv.conf',
        u'State': {u'ExitCode': 0,
                   u'FinishedAt': u'0001-01-01T00:00:00Z',
                   u'Paused': False,
                   u'Pid': 35327,
                   u'Running': True,
                   u'StartedAt': u'2014-08-22T08:49:57.906207449Z'},
        u'Volumes': {},
        u'VolumesRW': {}},
    "eba8bea2600029": {
        u'Args': [u'start', u'web'],
        u'Config': {u'AttachStderr': False,
                    u'AttachStdin': False,
                    u'AttachStdout': False,
                    u'Cmd': [u'start', u'web'],
                    u'CpuShares': 0,
                    u'Cpuset': u'',
                    u'Domainname': u'',
                    u'Entrypoint': [u'/runner/init'],
                    u'Env': [u'HMRC_CONFIG=-Dapplication.log=INFO -Drun.mode=Prod -Dlogger.resource=/application-json-logger.xml -Dhttp.port=8080',
                             u'JAVA_OPTS=-Xmx256m -Xms256m',
                             u'SLUG_URL=http://example.com/paye/paye_216.tgz',
                             u'PORT=8080',
                             u'HOME=/',
                             u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'],
                    u'ExposedPorts': {u'8080/tcp': {}},
                    u'Hostname': u'eba8bea26000',
                    u'Image': u'hmrc/slugrunner',
                    u'Memory': 0,
                    u'MemorySwap': 0,
                    u'NetworkDisabled': False,
                    u'OnBuild': None,
                    u'OpenStdin': False,
                    u'PortSpecs': None,
                    u'StdinOnce': False,
                    u'Tty': False,
                    u'User': u'',
                    u'Volumes': None,
                    u'WorkingDir': u''},
        u'Created': u'2014-08-22T08:34:08.134031634Z',
        u'Driver': u'aufs',
        u'ExecDriver': u'native-0.2',
        u'HostConfig': {u'Binds': None,
                        u'ContainerIDFile': u'',
                        u'Dns': None,
                        u'DnsSearch': None,
                        u'Links': None,
                        u'LxcConf': [],
                        u'NetworkMode': u'bridge',
                        u'PortBindings': {u'8080/tcp': [{u'HostIp': u'0.0.0.0',
                                                         u'HostPort': u'9317'}]},
                        u'Privileged': False,
                        u'PublishAllPorts': False,
                        u'VolumesFrom': None},
        u'HostnamePath': u'/var/lib/docker/containers/eba8bea2600029/hostname',
        u'HostsPath': u'/var/lib/docker/containers/eba8bea2600029/hosts',
        u'Id': u'eba8bea2600029',
        u'Image': u'c0cd53268e0c7c42bac84b6bf4f51561720c33f5239aa809f1135cc69cc73a2a',
        u'MountLabel': u'',
        u'Name': u'/paye_216',
        u'NetworkSettings': {u'Bridge': u'docker0',
                             u'Gateway': u'172.17.42.1',
                             u'IPAddress': u'172.17.3.221',
                             u'IPPrefixLen': 16,
                             u'PortMapping': None,
                             u'Ports': {u'8080/tcp': [{u'HostIp': u'0.0.0.0',
                                                       u'HostPort': u'9317'}]}},
        u'Path': u'/runner/init',
        u'ProcessLabel': u'',
        u'ResolvConfPath': u'/etc/resolv.conf',
        u'State': {u'ExitCode': 0,
                   u'FinishedAt': u'0001-01-01T00:00:00Z',
                   u'Paused': False,
                   u'Pid': 30996,
                   u'Running': True,
                   u'StartedAt': u'2014-08-22T08:34:08.260419303Z'},
        u'Volumes': {},
        u'VolumesRW': {}},
    "1ca0e49fcd60fa": {
        u'Args': [u'start', u'web'],
        u'Config': {u'AttachStderr': False,
                    u'AttachStdin': False,
                    u'AttachStdout': False,
                    u'Cmd': [u'start', u'web'],
                    u'CpuShares': 0,
                    u'Cpuset': u'',
                    u'Domainname': u'',
                    u'Entrypoint': [u'/runner/init'],
                    u'Env': [u'HMRC_CONFIG=-Dapplication.log=INFO -Drun.mode=Prod -Dlogger.resource=/application-json-logger.xml -Dhttp.port=8080',
                             u'JAVA_OPTS=-Xmx256m -Xms256m',
                             u'SLUG_URL=http://example.com/attorney/attorney_46.tgz',
                             u'PORT=8080',
                             u'HOME=/',
                             u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'],
                    u'ExposedPorts': {u'8080/tcp': {}},
                    u'Hostname': u'1ca0e49fcd60',
                    u'Image': u'hmrc/slugrunner',
                    u'Memory': 0,
                    u'MemorySwap': 0,
                    u'NetworkDisabled': False,
                    u'OnBuild': None,
                    u'OpenStdin': False,
                    u'PortSpecs': None,
                    u'StdinOnce': False,
                    u'Tty': False,
                    u'User': u'',
                    u'Volumes': None,
                    u'WorkingDir': u''},
        u'Created': u'2014-08-21T16:56:04.199712498Z',
        u'Driver': u'aufs',
        u'ExecDriver': u'native-0.2',
        u'HostConfig': {u'Binds': None,
                        u'ContainerIDFile': u'',
                        u'Dns': None,
                        u'DnsSearch': None,
                        u'Links': None,
                        u'LxcConf': [],
                        u'NetworkMode': u'bridge',
                        u'PortBindings': {u'8080/tcp': [{u'HostIp': u'0.0.0.0',
                                                         u'HostPort': u'9344'}]},
                        u'Privileged': False,
                        u'PublishAllPorts': False,
                        u'VolumesFrom': None},
        u'HostnamePath': u'/var/lib/docker/containers/1ca0e49fcd60fa/hostname',
        u'HostsPath': u'/var/lib/docker/containers/1ca0e49fcd60fa/hosts',
        u'Id': u'1ca0e49fcd60fa',
        u'Image': u'c0cd53268e0c7c42bac84b6bf4f51561720c33f5239aa809f1135cc69cc73a2a',
        u'MountLabel': u'',
        u'Name': u'/attorney_46',
        u'NetworkSettings': {u'Bridge': u'',
                             u'Gateway': u'',
                             u'IPAddress': u'',
                             u'IPPrefixLen': 0,
                             u'PortMapping': None,
                             u'Ports': None},
        u'Path': u'/runner/init',
        u'ProcessLabel': u'',
        u'ResolvConfPath': u'/etc/resolv.conf',
        u'State': {u'ExitCode': -1,
                   u'FinishedAt': u'2014-08-22T08:34:24.959801074Z',
                   u'Paused': False,
                   u'Pid': 0,
                   u'Running': False,
                   u'StartedAt': u'2014-08-21T16:56:04.913708838Z'},
        u'Volumes': {},
        u'VolumesRW': {}}
}


containers = [
    {"id": "656ca7c307d178", "app": "ers-checking-frontend-27", "version": None, "port": 9225, "running": True},
    {"id": "eba8bea2600029", "app": "paye", "version": "216", "port": 9317, "running": True},
    {"id": "1ca0e49fcd60fa", "app": "attorney", "version": "46", "port": 9344, "running": False},
]
container_details = __inspect_container_cmd_return
